// <auto-generated />
using System;
using Microblog.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Microblog.Migrations
{
    [DbContext(typeof(MicroblogContext))]
    [Migration("20230519035718_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microblog.Models.BlogPost", b =>
                {
                    b.Property<int>("BlogPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogPostId"), 1L, 1);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BlogPostId");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            BlogPostId = 1,
                            Category = "Personal",
                            Content = "lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu.",
                            CreatedDate = new DateTime(2023, 5, 18, 20, 57, 18, 75, DateTimeKind.Local).AddTicks(6725),
                            Title = "Chilaquiles verdes please",
                            UpdatedDate = new DateTime(2023, 5, 18, 20, 57, 18, 75, DateTimeKind.Local).AddTicks(6736)
                        },
                        new
                        {
                            BlogPostId = 2,
                            Category = "Development",
                            Content = "lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu.",
                            CreatedDate = new DateTime(2023, 5, 18, 20, 57, 18, 75, DateTimeKind.Local).AddTicks(6737),
                            Title = "Aspiring polymath",
                            UpdatedDate = new DateTime(2023, 5, 18, 20, 57, 18, 75, DateTimeKind.Local).AddTicks(6738)
                        },
                        new
                        {
                            BlogPostId = 3,
                            Category = "Travel",
                            Content = "lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu.",
                            CreatedDate = new DateTime(2023, 5, 18, 20, 57, 18, 75, DateTimeKind.Local).AddTicks(6739),
                            Title = "Mexico born, Texas raised",
                            UpdatedDate = new DateTime(2023, 5, 18, 20, 57, 18, 75, DateTimeKind.Local).AddTicks(6740)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
